name: Check In
on: [push]

jobs:
  build:
    runs-on: windows
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        run: pnpm install

      - name: Test
        run: pnpm test:run

      - name: Build
        run: |
          $env:VERSION = (git describe --tags --always --dirty) -replace '^v', ''
          pnpm build

      - name: Create release
        if: startsWith(gitea.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/bark-push.user.js

      - name: Move nightly tag
        if: startsWith(gitea.ref, 'refs/heads/')
        run: |
          git config user.name "Gitea Actions[bot]"
          git config user.email "actions@noreply.xuesong.eu.org"
          git push --delete origin nightly 2>$null
          git tag --force nightly
          git push origin nightly --force

      - name: Create nightly release
        if: startsWith(gitea.ref, 'refs/heads/')
        uses: akkuman/gitea-release-action@v1
        with:
          prerelease: true
          name: "Nightly Build"
          tag_name: "nightly"
          files: dist/bark-push.user.js
