name: Check In
on: [push]

jobs:
  build:
    runs-on: windows
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        run: pnpm install
      - name: Test
        run: pnpm test:run
      - name: Build
        run: pnpm build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/bark-push.user.js
